# Generated by Django 4.2.1 on 2023-07-10 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('subject', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('grade', models.CharField(max_length=50)),
            ],
        ),
    ]
